### ISSUE TITLE
Error while provisioning

### ISSUE THREAD

**Issue by cwiz** [kwrazi/archlinux-ros-melodic#1]
I'm building melodic-base on manjaro host.

At some point while building it I get following error:

 melodic: ==> Making package: ros-melodic-rospack 2.5.2-1 (Tue 26 Feb 2019 13:38:31 AEDT)
    melodic: ==> Checking runtime dependencies...
    melodic: ==> Installing missing dependencies...
    melodic: error: target not found: python-rosdep
    melodic: ==> ERROR: 'pacman' failed to install missing dependencies.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by kwrazi** [comment]
As a quick fix, manually install python-rosdep (with yaourt) before continuing (i.e. re-run) the provision.sh script. Currently verifying the issue.

**Comment by cwiz** [comment]
Some other packages I had to install from vagrant ssh

python-rosdep
ros-melodic-roslib
ros-melodic-rosconsole
ros-melodic-cmake-modules
ros-melodic-std-msgs

**Comment by cwiz** [comment]
Seems like issue is due to yaourt syncing database with each install. Since full install is huge, either ISP or server was resetting connection to download unchanged package index.

**Comment by kwrazi** [comment]
Thanks for the suggestion. I've remove excessive syncing to package databases. I hope that helps
